#8744 stop docker container when running not-interactively and pressing ctrl+c

diff --git a/ide b/ide
--- a/ide
+++ b/ide
@@ -3,6 +3,8 @@
 # http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 source "${DIR}/ide_functions"
+GREEN='\033[0;32m'
+NC='\033[0m'
 
 helpfunc() {
     echo "Usage: $0 [--group GROUP] [--idefile IDEFILE] COMMAND"
@@ -19,8 +21,20 @@ helpfunc() {
 # $2 is the file with environment variables to be mounted into docker container
 construct_docker_command() {
   env_file="$1"
+  run_interactively="$2"
+  run_id="$3"
+  # command can be left not specified, so let it be the last argument
+  command="$4"
   if [ -z "$env_file" ]; then
     log_error "env_file not specified"
+    return 1;
+  fi
+  if [ -z "$run_id" ]; then
+    log_error "run_id not specified"
+    return 1;
+  fi
+  if [ -z "$run_interactively" ]; then
+    log_error "run_interactively not specified"
     return 1;
   fi
 
@@ -37,10 +51,11 @@ construct_docker_command() {
       docker_cmd+=" $IDE_DOCKER_OPTIONS"
   fi
 
-  if [ -t 0 ]; then
-      # interactive shell
+  if [[ "$run_interactively" == "true" ]]; then
       docker_cmd+=" -ti"
   fi
+
+  docker_cmd+=" --name ${run_id}"
 
   if [ -n "$command" ]; then
       # $command set
@@ -88,6 +103,9 @@ do
         ;;
     --dryrun)
         dryrun="true"
+        ;;
+    --force_not_interactive)
+        force_not_interactive="true"
         ;;
     --*)
         log_error "Invalid option: '$opt'" >&2
@@ -163,21 +181,59 @@ if [ -z "$IDE_VARS_BLACKLIST" ]; then
   IDE_VARS_BLACKLIST="BASH*,HOME,USERNAME,USER,LOGNAME,PATH,TERM,SHELL,MAIL,SUDO_*,WINDOWID,SSH_*,SESSION_*,GEM_HOME,GEM_PATH,GEM_ROOT,HOSTNAME,HOSTTYPE,IFS,PPID,PWD,OLDPWD"
   log_debug "IDE_VARS_BLACKLIST not set, setting to: $IDE_VARS_BLACKLIST"
 fi
+if [ -t 0 ] && [[ -z "$force_not_interactive" ]]; then
+  # shell is really interactive and "$force_not_interactive" is not set
+  run_interactively="true"
+else
+  run_interactively="false"
+fi
+log_debug "run_interactively: $run_interactively"
 
-env_file=$(get_env_vars_file_name)
+# it serves here as an identificator, will be used as docker container name
+# and as a part of env_file
+run_id=$(get_run_id)
+env_file=$(get_env_vars_file_name ${run_id})
 env_dir=$(dirname "${env_file}")
 mkdir -p "${env_dir}"
 save_environment_variables "$env_file" "$IDE_VARS_BLACKLIST"
 
 # construct docker command
-docker_command=$(construct_docker_command "$env_file" "$command")
-echo -e "docker command would be:\n${docker_command}"
+docker_command=$(construct_docker_command "$env_file" "$run_interactively" "$run_id" "$command")
+echo -e "docker command will be:\n${GREEN}${docker_command}${NC}"
+
+on_control_c()
+{
+    log_error "Ctrl+c caught by IDE."
+    if [[ $(docker inspect -f {{.State.Running}} $run_id ) == "false" ]]; then
+      # If Ctrl+c was typed fast enough, docker container is not running, but
+      # it is created. If that is the case, remove it.
+      log_error "I will remove docker container: $run_id (it was created but not started)"
+      docker rm "$run_id"
+    else
+      log_error "I will stop docker container: $run_id"
+      # this can still take some time (up to 10 seconds)
+      docker stop "$run_id"
+    fi
+}
+trap 'on_control_c' INT
 
 # run docker run
 if [[ "$dryrun" != "true" ]]; then
-  eval "$docker_command"
+  if [[ "$run_interactively" == "true" ]]; then
+    eval "${docker_command}"
+  else
+    # run in the background so that user has a moment to run ctrl+c
+    # until container did not stop
+    eval "${docker_command}" &
+  fi
+  docker_command_pid=$!
+  wait $docker_command_pid
   exit_status="$?"
+  log_debug "ide exit status: $exit_status"
   if [[ "$exit_status" != "0" ]]; then
+    log_error "fail! exit status: $exit_status"
     exit $exit_status
   fi
 fi
+
+rm -rf "${env_file}"
